# The URL the site will be built for
title = ""
description = "Blog of Gabriel Falcão, author of python open source projects HTTPretty, Sure. Original author of Guake Terminal and several other open source projects in the programming languages: Rust, Python, Typescript, Javascript and more."
base_url = "https://gabrielfalcao.github.io"
feed_filenames = ["atom.xml"]
generate_feeds = true
minify_html = true
default_language = "en"
generate_sitemap = true
generate_robots_txt = true
build_search_index = true
compile_sass = true


# theme = "terminus"
# theme = "tale-zola"
# theme = "tranquil"
# theme = "boring"
theme = "hook"


[markdown]
render_emoji = false
external_links_target_blank = true

external_links_no_follow = false
# It tells search engine crawlers (like Google) not to follow the link or use it for page ranking calculations


external_links_no_referrer = false
# According to the MDN Web Docs definition, rel="noreferrer" is an HTML attribute value that hides referrer information
# and enhances security when a user navigates to an external link


external_links_external = false
# According to the MDN Web Docs rel attribute reference, the rel="external" attribute indicates that the referenced
# document is not part of the current site


# Explicit Examples
# [Visit External Site](https://example.com){rel="external nofollow"}



[markdown.highlighting]
theme = "monokai"

[extra]
# Put all your custom variables here
